<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body { font-family: sans-serif; line-height: 1.6; color: #333; }
        h1, h2, h3 { color: #1a202c; margin-bottom: 0.5em; }
        h1 { font-size: 24px; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-bottom: 20px; }
        h2 { font-size: 18px; margin-top: 20px; }
        h3 { font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .section { margin-bottom: 30px; }
        .page-break { page-break-after: always; }
        .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 50px; text-align: center; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <div class="footer">
        Report Generated: {{ now()->format('Y-m-d H:i:s') }} | Page <span class="page-number"></span>
    </div>

    <h1>{{ $report->title }}</h1>
    <p><strong>Case Number:</strong> {{ $report->case->case_number }}</p>
    <p><strong>Report Version:</strong> {{ $report->version }}</p>
    <p><strong>Generated By:</strong> {{ $report->createdBy->name }}</p>
    <p><strong>Date Generated:</strong> {{ $report->updated_at->format('Y-m-d H:i') }}</p>

    {{-- Render Sections based on $content passed from Job --}}
    @foreach($content as $key => $sectionData)
        <div class="section">
            <h2>{{ $sectionData['title'] ?? ucfirst(str_replace('_', ' ', $key)) }}</h2>

            @if(isset($sectionData['message']))
                <p>{{ $sectionData['message'] }}</p>
            @elseif($key === 'case_summary')
                <p><strong>Firearm Type:</strong> {{ $sectionData['firearm_type'] }}</p>
                <p><strong>Opened Date:</strong> {{ $sectionData['opened_date'] }}</p>
                <p><strong>Status:</strong> {{ $sectionData['status'] }}</p>
            @elseif($key === 'ballistics_analysis')
                 <p><strong>Algorithm:</strong> {{ $sectionData['algorithm'] }}</p>
                 <p><strong>Performed At:</strong> {{ $sectionData['performed_at'] }}</p>
                 <p><strong>Duration:</strong> {{ $sectionData['duration'] ?? 'N/A' }} seconds</p>
                 <p><strong>Performed By:</strong> {{ $sectionData['performed_by'] }}</p>
            @elseif($key === 'match_results')
                {{-- Render match results table --}}
                <p>Match results details placeholder.</p>
            @elseif($key === 'images')
                 {{-- Render images --}}
                 <p>Image gallery placeholder.</p>
            @elseif($key === 'conclusions')
                 {{-- Render conclusions --}}
                 <p>Conclusions placeholder.</p>
            @else
                {{-- Default rendering for unknown sections --}}
                @if(is_array($sectionData))
                    <ul>
                    @foreach($sectionData as $subKey => $value)
                        <li><strong>{{ ucfirst(str_replace('_', ' ', $subKey)) }}:</strong> {{ is_array($value) ? json_encode($value) : $value }}</li>
                    @endforeach
                    </ul>
                @else
                    <p>{{ $sectionData }}</p>
                @endif
            @endif
        </div>
    @endforeach

    {{-- Add page number script for DomPDF --}}
    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 10;
            $font = $fontMetrics->getFont("helvetica");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 35;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>
